version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10.18.1
        environment:
          TERM: xterm

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Tests
          command: npm run test:ci

      - run:
          name: Coverage
          command: npm run coveralls

      - save_cache:
          name: Save node_modules cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy_tag:
      filters:
        tags:
          only: /.*/

      docker:
        - image: cypress/base:10.18.1
          environment:
            TERM: xterm

      working_directory: ~/repo

      steps:
        - checkout

        - run:
            name: Install dependencies
            command: npm install

        - run:
            name: Build source
            command: npm run build

        - run:
            name: Authenticate with registry
            command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

        - run:
            name: Publish package
            command: npm publish
